### ISSUE TITLE
Needs to handle special characters in passwords

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-CIDA/cida-auth#63]
@isuftin the word on the street is that all we have to do to get this to work for CCH is escape special characters in the password. Also, that you may have written that part ;)

**Comment by isuftin** [comment]
What's a special character?

**Comment by jiwalker-usgs** [comment]
anything that is url encoded.  Things are getting encoded but not decoded anywhere.

**Comment by jkreft-usgs** [comment]
If this issue means that people with valid AD passwords are sometimes not going to be able to log in to apps that use cida-auth, this is a pretty big deal.

**Comment by isuftin** [comment]
@mhines-usgs How was this problem discovered? Who had/has an issue?

**Comment by jiwalker-usgs** [comment]
@isuftin we created a service account for CCH and the characters used caused it not to work, it seemed to be because of url encoding

**Comment by thongsav-usgs** [comment]
@jkreft-usgs yes, it's a pretty big bug. 

We should have fixed it during the CCH release instead of working around it. It's fairly low complexity to fix, if CCH doesn't have spare cycles now, we can get it into Kanban or another project.

**Comment by isuftin** [comment]
This may be an issue with the way the service account user is set up and not the application itself.

**Comment by thongsav-usgs** [comment]
I have to change my AD password anyway. I'll update this ticket sometime this later this week.

**Comment by mhines-usgs** [comment]
Emailed Ben F to see if he could verify Ivan's suspicions.

**Comment by isuftin** [comment]
The application is throwing an NPE here: https://github.com/USGS-CIDA/cida-auth/blob/auth-parent-1.1.0/auth-service/src/main/java/gov/usgs/cida/auth/service/authentication/LDAPService.java#L90

This means that the "mail" attribute may not exist on this service account. 

I will wait for more info to come in before pursuing this any further.

**Comment by thongsav-usgs** [comment]
:+1:

**Comment by thongsav-usgs** [comment]
I just put a debugger on the whole process and can confirm @isuftin's suspicions. All special characters are properly being communicated. 

Closing this ticket. The NPE is a bug, but much lower impact and we will address that later.

**Comment by thongsav-usgs** [comment]
Not an issue.
